### ISSUE TITLE
Add cache database functionality

### ISSUE THREAD

**Issue by mgrover1** [NCAR/esds-funnel#11]
@andersy005 

I have been playing around with a potential class for this functionality... would we want the dataset to look something like this?

![Screen Shot 2021-07-01 at 10 51 06 AM](https://user-images.githubusercontent.com/26660300/124161119-42f20080-da5a-11eb-9b98-0a48865a6ea8.png)

Then, when someone accesses this, they would use
```python
test = df.iloc[0]
new_cache = funnel.CacheStore(test.cache_dir)
read_ds = new_cache.get(test.name, test.serializer)
```

**Comment by andersy005** [comment]
We want to avoid recording the `cache_dir` and `path` in this database. The cache path information should be in the `CacheStore`. This would allow the user to move their cache artifacts from one location (e.g. directory/s3 bucket) to another location without needing to update the actual database. By querying the database for information about a particular cache artifact, we get the necessary information such as the `serializer` that we then can use to access the asset from the cache store. 

I consider the `CacheStore` and the `Database` classes/objects to be low-level objects. We will need a third --high-level-- class that the user will interact with. This class will take care of interfacing with the database and the cache store on behalf of the user.

**Comment by mgrover1** [comment]
Now that that smaller piece is in place, I can start piecing together that third "high-level" class that user will interact with, using Matt's initial implementation for inspiration...

**Comment by mgrover1** [comment]
Here is a start to building a cache database, building off of what Matt originally put together, with a few tweaks... the main part here is taking some dictionary with the catalog information, query, functions, etc., and attaching to some asset (ex. netcdf file)

``` python
class EsmMetadataStore(object):
    def __init__(self,
                 metadata_dictionary,
                 cache_catalog_directory='.',
                 cache_catalog_prefix='',
                ):
        
        self.metadata_dictionary = metadata_dictionary
        
    
    def find_cache_id_files(self):
        return sorted(glob(f'{cache_catalog_directory}/{cache_catalog_prefix}*.yml'))   
    
    def assemble_cache_database(self):
        self.cache_files = {}
        
        cache_id_files = self.find_cache_id_files()

        
        if cache_id_files:
            for file in cache_id_files:
 
                try:
                    with open(file, 'r') as fid:
                        cache_id = yaml.load(fid, Loader=yaml.Loader)
                except: # TODO: be more informative here
                    print(f'cannot read cache: {file}...skipping')
                    print('skipping')
                    
                cache_origins_dict = {
                    k: cache_id[k] 
                    for k in self.metadata_dictionary.keys()
                    if k in cache_id
                }
                print(cache_origins_dict)
                if cache_origins_dict == self.metadata_dictionary:
                    variable = cache_id['variable']
                    key = cache_id['esm_collection_key']
                    if variable not in self.cache_files:
                        self.cache_files[variable] = {}                        
                    self.cache_files[variable][key] = cache_id['asset']
```

**Comment by andersy005** [comment]
@mgrover1, It would be easier to iterate on this in a PR...Could you open a PR when you get a moment?


The `MetadataStore` class should be a subclass of the https://github.com/NCAR/esds-funnel/blob/43cba1fc41c9e22fcddb1d480506933f0be35273/funnel/metadata.py#L11



and this subclass should implement these methods

https://github.com/NCAR/esds-funnel/blob/43cba1fc41c9e22fcddb1d480506933f0be35273/funnel/metadata.py#L29-L36
