### ISSUE TITLE
Variable Database

### ISSUE THREAD

**Issue by mgrover1** [NCAR/esds-funnel#21]
Would it make sense to have a variable database as well as a cache database? The collection object could have a pandas dataframe representation of the variables available (directly from the catalog), as well as a  list of derived variables... when one adds another derived variable to the `derived_variables` registry, it would add it here... this could fall within the `derive`module.

**Comment by matt-long** [comment]
How does the database extend beyond the functionality of the registry? 

I could see some important possibilities, like include metadata describing the expected behavior of some functions (like the dimensions over which it aggregates?).

**Comment by mgrover1** [comment]
It could contain information about what arguments are expected, dimensions over which it aggregates, etc.It would also be easier, from a user perspective, to see what variables are available

**Comment by andersy005** [comment]
Addressed by https://github.com/intake/intake-esm/pull/379
