### ISSUE TITLE
intake dataset transforms aka derived datasets

### ISSUE THREAD

**Issue by dcherian** [NCAR/esds-funnel#26]
intake has this derived dataset functionality that I haven't used> the documentation doesn't seem very friendly though

https://intake.readthedocs.io/en/latest/transforms.html

**Comment by mgrover1** [comment]
Interesting... I am trying to think what this would look like in the context of this package... this would be good to discuss at the upcoming funnel dev meeting

**Comment by andersy005** [comment]
Addressed by https://github.com/intake/intake-esm/pull/379
