### ISSUE TITLE
Add Documentation 

### ISSUE THREAD

**Issue by andersy005** [NCAR/esds-funnel#50]
- [x] Set up documentation build on RTD
- [x] Add template for docs
- [ ] Add demos on `CacheStore` and `FunnelResult`

**Comment by kmpaul** [comment]
- [ ] Add documentation on how to use Prefect for diagnostics (i.e., simple intro / doesn't replace Prefect's own documentation)

**Comment by mgrover1** [comment]
We should probably update the docs to reflect this being more of an **example** repository - can we repurpose the existing documentation infrastructure?

**Comment by andersy005** [comment]
@mgrover1, #62 removes the existing/unused code. So, feel free to repurpose this... A jupyterbook is one option (we could use https://jupyterbook.org/publish/readthedocs.html) to still take advantage of readthedocs, etc...
